[package]
name = "leafc_macros"
description = "Macros used by leafc, both procedural and declarative"
keywords = ["leafc", "macros", "declarative", "procedural", "proc-macro"]

version.workspace = true
categories.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true

[lib]
doctest = true

[features]
default = ["multi-threaded", "serde", "allocative"]
all = ["multi-threaded", "serde", "allocative", "no-std"]
multi-threaded = []
# multi-threaded = ["dep:atomic", "dep:parking_lot", "dep:crossbeam_utils"]
serde = ["dep:serde"]
no-std = []
allocative = ["dep:allocative"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = { workspace = true }
allocative = { workspace = true, optional = true }
cfg-if = { workspace = true }
proc-macro2 = { workspace = true }
serde = { workspace = true, optional = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
syn = { workspace = true }
quote = { workspace = true }
