[package]
name = "leafcdb"
version = "0.1.0"
description = "Debugger for Leafc built within a TUI environment"
keywords = ["compiler", "debugger", "tui"]

authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
