[book]
authors = ["pulanski"]
language = "en"
multilingual = false
src = "src"
title = "The Leaf Reference"
description = "A reference for the Leafc Compiler"

[output.html.print]
enable = true

[output.pdf]
optional = true

[output.html]
