[package]
name = "leafc_intern"
version = "0.1.0"
description = "Leafc's interning system, which is used to intern strings and other data structures within the compiler used during the compilation lifecycle."
keywords = ["leafc", "interning", "string", "string interning", "compiler"]

categories.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true

[lib]
doctest = true

[features]
default = []
multi-threaded = ["lasso/multi-threaded"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leafc_utils = { path = "../leafc_utils" }

lasso = { workspace = true }
derive_more = { workspace = true }

[dev-dependencies]
pretty_assertions_sorted = { workspace = true }
rstest = { workspace = true }
